import fp from 'fastify-plugin';
import { FastifyPluginAsync } from 'fastify';
import { PrismaClient } from '@prisma/client';

declare module 'fastify' {
    interface FastifyInstance {
        prisma: PrismaClient;
    }
}

/**
 * this plugin does the following:
 * - register prisma client to be accessible through `fastify.prisma`
 * - register prisma schemas generated by `prisma-json-schema-generator` for serialization & validation 
 */
export const PrismaPlugin: FastifyPluginAsync = fp(async (fastify, options) => {
    const prisma = new PrismaClient();
    await prisma.$connect();

    fastify
        .decorate('prisma', prisma)
        .addSchema(require('../prisma/json-schema/json-schema.json'))
        .addHook('onClose', async (server) => {
            await server.prisma.$disconnect();
        });
});
